name: Release Service

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*'

jobs:
  ReleasePackage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Get StartOS Hash
        run: echo "EMBASSYHASH=$(git ls-remote https://github.com/Start9Labs/start-os --branch latest | awk '{ print $1}')" >> $GITHUB_ENV
      - name: Cache Packages
        uses: buildjet/cache@v3
        id: packageCache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-simplex-${{ env.EMBASSYHASH }}
      - name: Install Dependencies
        run: |
          sudo snap install yq deno
          sudo apt-get install -y build-essential openssl libssl-dev libc6-dev clang libclang-dev ca-certificates
      - name: Checkout services repository
        uses: actions/checkout@v3
      - name: Install Package Manager
        id: packageManager
        if: steps.packageCache.outputs.cache-hit != 'true'
        run: |
          cd ~/ && git clone https://github.com/Start9Labs/start-os.git --branch latest;
          cd start-os;
          git submodule update --init --recursive
          cd backend;
          export RUSTFLAGS="";
          export OS_ARCH=$(uname -m);
          ./install-sdk.sh;
          cargo install --git=https://github.com/Start9Labs/md-packer.git --branch=main;
      - name: Build the service package
        run: |
          git submodule update --init --recursive
          embassy-sdk init
          make
      - name: Generate sha256 checksum
        run: |
          sha256sum simplex.s9pk > simplex.s9pk.sha256
      - name: Generate changelog
        run: |
          echo "## What's Changed" > change-log.txt
          yq e '.release-notes' manifest.yaml >> change-log.txt
          echo >> change-log.txt
          echo "### SHA 256 Hash" >> change-log.txt
          echo "\`$(sha256sum simplex.s9pk)\`" >> change-log.txt
          sha256sum simplex.s9pk >> change-log.txt
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: SimpleX Server ${{ github.ref_name }}
          body_path: change-log.txt
          files: |
            simplex.s9pk
            simplex.s9pk.sha256
